#include "theme.h"
#include "gfx.h"

struct theme theme_acid = {
	COL(WHITE, BLACK),
	COL(BLACK, WHITE),

	COL(RED, BRIGHT(YELLOW)),
	COL(BRIGHT(YELLOW), MAGENTA),
	COL(MAGENTA, RED),
	COL(BRIGHT(WHITE), RED),

	COL(BRIGHT(WHITE), GREEN),
	COL(BRIGHT(YELLOW), BRIGHT(CYAN)),
	COL(GREEN, BLUE),
	COL(BRIGHT(WHITE), BLUE),
	COL(GREEN, BRIGHT(WHITE)),

	COL(BRIGHT(WHITE), RED),
	COL(RED, BRIGHT(WHITE)),
	COL(BRIGHT(YELLOW), BLUE),
	COL(BLUE, BRIGHT(YELLOW)),
};

struct theme theme_data = {
	COL(GREEN, BLACK),
	COL(BLACK, GREEN),

	COL(BRIGHT(WHITE), BRIGHT(GREEN)),
	COL(BRIGHT(GREEN), BLACK),
	COL(BRIGHT(GREEN), BLACK),
	COL(BRIGHT(WHITE), BLACK),

	COL(BRIGHT(GREEN), BLACK),
	COL(BLACK, BRIGHT(GREEN)),
	COL(BRIGHT(GREEN), BLACK),
	COL(BRIGHT(WHITE), BLACK),
	COL(BLACK, BRIGHT(GREEN)),

	COL(BLACK, GREEN),
	COL(BRIGHT(GREEN), BLACK),
	COL(BLACK, GREEN),
	COL(BRIGHT(GREEN), BLACK),
};

struct theme theme_borland = {
	COL(WHITE, BLACK),
	COL(BLACK, WHITE),

	COL(WHITE, BRIGHT(YELLOW)),
	COL(BRIGHT(YELLOW), BLUE),
	COL(BRIGHT(YELLOW), BLUE),
	COL(BRIGHT(WHITE), BLUE),

	COL(BRIGHT(YELLOW), BLUE),
	COL(WHITE, BRIGHT(YELLOW)),
	COL(BRIGHT(YELLOW), BLUE),
	COL(BRIGHT(WHITE), BLUE),
	COL(BLUE, BRIGHT(YELLOW)),

	COL(BLUE, WHITE),
	COL(BRIGHT(YELLOW), BLUE),
	COL(BLUE, WHITE),
	COL(BRIGHT(YELLOW), BLUE),
};

struct theme *theme_cur = &theme_data;
